---
driver:
  name: docker
  # Workaround for test-kitchen/kitchen-docker Issue #207
  use_sudo: false

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  ansible_verbose: false
  ansible_verbosity: 2

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: centos-7

suites:
  - name: codedeploy-agent
    run_list:
    attributes:
